#image: ocaml/opam2:4.10
image: kakadu18/ocaml:fp2020 # an iamge for this course

stages:
  - build
  - test

build:
  # https://docs.gitlab.com/ee/ci/yaml/#cache
  stage: build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - _opam
  script:
    - sh -exc "./build_latest.sh build"
    - sh -exc "./build_latest.sh test"
      #- '[ -d _opam ] || cp -r ~/.opam/4.07 _opam'
      #- sudo apt install m4 -y
      #- opam install --deps-only -t -y .

# test:
#   stage: test
#   cache:
#     key: "$CI_COMMIT_REF_SLUG"
#     paths:
#       - _opam
#   script:
#     - sh -exc "./build_latest.sh test"
#- eval $(opam env)
#- opam switch
#- dune runtest
